// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/ledger.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 扩展输入
type TxInputExt struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	RefTxid              []byte   `protobuf:"bytes,3,opt,name=ref_txid,json=refTxid,proto3" json:"ref_txid,omitempty"`
	RefOffset            int32    `protobuf:"varint,4,opt,name=ref_offset,json=refOffset,proto3" json:"ref_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxInputExt) Reset()         { *m = TxInputExt{} }
func (m *TxInputExt) String() string { return proto.CompactTextString(m) }
func (*TxInputExt) ProtoMessage()    {}
func (*TxInputExt) Descriptor() ([]byte, []int) {
	return fileDescriptor_f844dbfbee8dd993, []int{0}
}

func (m *TxInputExt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxInputExt.Unmarshal(m, b)
}
func (m *TxInputExt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxInputExt.Marshal(b, m, deterministic)
}
func (m *TxInputExt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxInputExt.Merge(m, src)
}
func (m *TxInputExt) XXX_Size() int {
	return xxx_messageInfo_TxInputExt.Size(m)
}
func (m *TxInputExt) XXX_DiscardUnknown() {
	xxx_messageInfo_TxInputExt.DiscardUnknown(m)
}

var xxx_messageInfo_TxInputExt proto.InternalMessageInfo

func (m *TxInputExt) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *TxInputExt) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *TxInputExt) GetRefTxid() []byte {
	if m != nil {
		return m.RefTxid
	}
	return nil
}

func (m *TxInputExt) GetRefOffset() int32 {
	if m != nil {
		return m.RefOffset
	}
	return 0
}

// 扩展输出
type TxOutputExt struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxOutputExt) Reset()         { *m = TxOutputExt{} }
func (m *TxOutputExt) String() string { return proto.CompactTextString(m) }
func (*TxOutputExt) ProtoMessage()    {}
func (*TxOutputExt) Descriptor() ([]byte, []int) {
	return fileDescriptor_f844dbfbee8dd993, []int{1}
}

func (m *TxOutputExt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOutputExt.Unmarshal(m, b)
}
func (m *TxOutputExt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOutputExt.Marshal(b, m, deterministic)
}
func (m *TxOutputExt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOutputExt.Merge(m, src)
}
func (m *TxOutputExt) XXX_Size() int {
	return xxx_messageInfo_TxOutputExt.Size(m)
}
func (m *TxOutputExt) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOutputExt.DiscardUnknown(m)
}

var xxx_messageInfo_TxOutputExt proto.InternalMessageInfo

func (m *TxOutputExt) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *TxOutputExt) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *TxOutputExt) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// Transaction input
type TxInput struct {
	// The transaction id referenced to
	RefTxid []byte `protobuf:"bytes,1,opt,name=ref_txid,json=refTxid,proto3" json:"ref_txid,omitempty"`
	// The output offset of the transaction referenced to
	RefOffset int32 `protobuf:"varint,2,opt,name=ref_offset,json=refOffset,proto3" json:"ref_offset,omitempty"`
	// The address of the launcher
	FromAddr []byte `protobuf:"bytes,5,opt,name=from_addr,json=fromAddr,proto3" json:"from_addr,omitempty"`
	// The amount of the transaction
	Amount []byte `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	// Frozen height
	FrozenHeight         int64    `protobuf:"varint,7,opt,name=frozen_height,json=frozenHeight,proto3" json:"frozen_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxInput) Reset()         { *m = TxInput{} }
func (m *TxInput) String() string { return proto.CompactTextString(m) }
func (*TxInput) ProtoMessage()    {}
func (*TxInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_f844dbfbee8dd993, []int{2}
}

func (m *TxInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxInput.Unmarshal(m, b)
}
func (m *TxInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxInput.Marshal(b, m, deterministic)
}
func (m *TxInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxInput.Merge(m, src)
}
func (m *TxInput) XXX_Size() int {
	return xxx_messageInfo_TxInput.Size(m)
}
func (m *TxInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TxInput.DiscardUnknown(m)
}

var xxx_messageInfo_TxInput proto.InternalMessageInfo

func (m *TxInput) GetRefTxid() []byte {
	if m != nil {
		return m.RefTxid
	}
	return nil
}

func (m *TxInput) GetRefOffset() int32 {
	if m != nil {
		return m.RefOffset
	}
	return 0
}

func (m *TxInput) GetFromAddr() []byte {
	if m != nil {
		return m.FromAddr
	}
	return nil
}

func (m *TxInput) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *TxInput) GetFrozenHeight() int64 {
	if m != nil {
		return m.FrozenHeight
	}
	return 0
}

// Transaction output
type TxOutput struct {
	// The amount of the transaction
	Amount []byte `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// The address of the launcher
	ToAddr []byte `protobuf:"bytes,2,opt,name=to_addr,json=toAddr,proto3" json:"to_addr,omitempty"`
	// Fronzen height
	FrozenHeight         int64    `protobuf:"varint,4,opt,name=frozen_height,json=frozenHeight,proto3" json:"frozen_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxOutput) Reset()         { *m = TxOutput{} }
func (m *TxOutput) String() string { return proto.CompactTextString(m) }
func (*TxOutput) ProtoMessage()    {}
func (*TxOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_f844dbfbee8dd993, []int{3}
}

func (m *TxOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOutput.Unmarshal(m, b)
}
func (m *TxOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOutput.Marshal(b, m, deterministic)
}
func (m *TxOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOutput.Merge(m, src)
}
func (m *TxOutput) XXX_Size() int {
	return xxx_messageInfo_TxOutput.Size(m)
}
func (m *TxOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TxOutput proto.InternalMessageInfo

func (m *TxOutput) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *TxOutput) GetToAddr() []byte {
	if m != nil {
		return m.ToAddr
	}
	return nil
}

func (m *TxOutput) GetFrozenHeight() int64 {
	if m != nil {
		return m.FrozenHeight
	}
	return 0
}

// 查询分红响应
type BonusQueryReply struct {
	// 分红数量
	Bonus int64 `protobuf:"varint,1,opt,name=bonus,proto3" json:"bonus,omitempty"`
	// 分红信息提示
	Info string `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// tdpos共识提名候选人需要质押治理代币的最少量
	TokenNeed            string   `protobuf:"bytes,3,opt,name=token_need,json=tokenNeed,proto3" json:"token_need,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BonusQueryReply) Reset()         { *m = BonusQueryReply{} }
func (m *BonusQueryReply) String() string { return proto.CompactTextString(m) }
func (*BonusQueryReply) ProtoMessage()    {}
func (*BonusQueryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f844dbfbee8dd993, []int{4}
}

func (m *BonusQueryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BonusQueryReply.Unmarshal(m, b)
}
func (m *BonusQueryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BonusQueryReply.Marshal(b, m, deterministic)
}
func (m *BonusQueryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BonusQueryReply.Merge(m, src)
}
func (m *BonusQueryReply) XXX_Size() int {
	return xxx_messageInfo_BonusQueryReply.Size(m)
}
func (m *BonusQueryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BonusQueryReply.DiscardUnknown(m)
}

var xxx_messageInfo_BonusQueryReply proto.InternalMessageInfo

func (m *BonusQueryReply) GetBonus() int64 {
	if m != nil {
		return m.Bonus
	}
	return 0
}

func (m *BonusQueryReply) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *BonusQueryReply) GetTokenNeed() string {
	if m != nil {
		return m.TokenNeed
	}
	return ""
}

func init() {
	proto.RegisterType((*TxInputExt)(nil), "protos.TxInputExt")
	proto.RegisterType((*TxOutputExt)(nil), "protos.TxOutputExt")
	proto.RegisterType((*TxInput)(nil), "protos.TxInput")
	proto.RegisterType((*TxOutput)(nil), "protos.TxOutput")
	proto.RegisterType((*BonusQueryReply)(nil), "protos.BonusQueryReply")
}

func init() { proto.RegisterFile("protos/ledger.proto", fileDescriptor_f844dbfbee8dd993) }

var fileDescriptor_f844dbfbee8dd993 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xd1, 0xca, 0xd3, 0x30,
	0x18, 0x86, 0xc9, 0xdf, 0xad, 0x5d, 0x3f, 0x7f, 0x51, 0xa2, 0x68, 0x45, 0x84, 0x52, 0x4f, 0x7a,
	0xe2, 0x2a, 0x7a, 0x05, 0x0e, 0x04, 0x3d, 0xd0, 0x61, 0xd8, 0xd1, 0x4e, 0x6a, 0xdb, 0x7c, 0x59,
	0xcb, 0xb6, 0xa4, 0xa4, 0x89, 0x74, 0xde, 0x8b, 0xf7, 0x2a, 0x4d, 0x2a, 0x38, 0x15, 0xe1, 0x3f,
	0xcb, 0xfb, 0x84, 0xe6, 0x79, 0xbf, 0x34, 0xf0, 0xa8, 0xd7, 0xca, 0xa8, 0xa1, 0x38, 0x21, 0x3f,
	0xa0, 0x5e, 0xbb, 0x44, 0x43, 0x0f, 0xb3, 0x1e, 0x60, 0x37, 0x7e, 0x94, 0xbd, 0x35, 0xef, 0x47,
	0x43, 0x9f, 0x40, 0x58, 0xdb, 0xe6, 0x88, 0x26, 0x21, 0x29, 0xc9, 0x63, 0x36, 0x27, 0xfa, 0x10,
	0x82, 0x23, 0x5e, 0x92, 0x9b, 0x94, 0xe4, 0xb7, 0x6c, 0x5a, 0xd2, 0x67, 0xb0, 0xd2, 0x28, 0x4a,
	0x33, 0x76, 0x3c, 0x09, 0x1c, 0x8e, 0x34, 0x8a, 0xdd, 0xd8, 0x71, 0xfa, 0x02, 0x60, 0xda, 0x52,
	0x42, 0x0c, 0x68, 0x92, 0x45, 0x4a, 0xf2, 0x25, 0x8b, 0x35, 0x8a, 0xad, 0x03, 0xd9, 0x27, 0xb8,
	0xb7, 0x1b, 0xb7, 0xd6, 0xdc, 0x59, 0xf9, 0x18, 0x96, 0xdf, 0xaa, 0x93, 0xc5, 0xd9, 0xe7, 0x43,
	0xf6, 0x83, 0x40, 0x34, 0x4f, 0x70, 0x55, 0x8a, 0xfc, 0xaf, 0xd4, 0xcd, 0x1f, 0xa5, 0xe8, 0x73,
	0x88, 0x85, 0x56, 0xe7, 0xb2, 0xe2, 0x5c, 0x27, 0x4b, 0xf7, 0xe9, 0x6a, 0x02, 0xef, 0x38, 0xd7,
	0x53, 0xc5, 0xea, 0xac, 0xac, 0x34, 0x49, 0xe8, 0x76, 0xe6, 0x44, 0x5f, 0xc2, 0x7d, 0xa1, 0xd5,
	0x77, 0x94, 0x65, 0x8b, 0xdd, 0xa1, 0x35, 0x49, 0x94, 0x92, 0x3c, 0x60, 0xb7, 0x1e, 0x7e, 0x70,
	0x2c, 0xfb, 0x0a, 0xab, 0x5f, 0xe3, 0xfe, 0x76, 0x10, 0xb9, 0x3a, 0xe8, 0x29, 0x44, 0x46, 0x79,
	0xb7, 0x9f, 0x37, 0x34, 0xca, 0x99, 0xff, 0x32, 0x2c, 0xfe, 0x61, 0xd8, 0xc3, 0x83, 0x8d, 0x92,
	0x76, 0xf8, 0x62, 0x51, 0x5f, 0x18, 0xf6, 0x27, 0x77, 0x55, 0xf5, 0x84, 0x9c, 0x27, 0x60, 0x3e,
	0x50, 0x0a, 0x8b, 0x4e, 0x0a, 0xe5, 0x1c, 0x31, 0x73, 0xeb, 0xe9, 0x5e, 0x8c, 0x3a, 0xa2, 0x2c,
	0x25, 0xa2, 0xff, 0x93, 0x31, 0x8b, 0x1d, 0xf9, 0x8c, 0xc8, 0x37, 0x6f, 0xf6, 0xaf, 0x0f, 0x9d,
	0x69, 0x6d, 0xbd, 0x6e, 0xd4, 0xb9, 0x18, 0x6c, 0x8f, 0xba, 0x51, 0x72, 0x40, 0x39, 0xd8, 0xe1,
	0x55, 0xd3, 0x56, 0x9d, 0x2c, 0x46, 0x0f, 0x35, 0x16, 0xfe, 0x49, 0xd5, 0xfe, 0x69, 0xbd, 0xfd,
	0x19, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xc6, 0x5f, 0x77, 0x78, 0x02, 0x00, 0x00,
}
